CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'to-do',
    due_date DATE NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0
);

